name: C/C++ CIr

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: debian-10

    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make install
      run: make install
