name: main
on: [push]
jobs:
  execute-CompileNTP:
    runs-on: self-hosted
    steps:
      - run: bash
      - run: push /root/ntp/ntp-4.2.8p15/ ; ./configure ; cd /root/ntp/ntp-4.2.8p15/ntpq/ ; ls -l ; make ; pop
